# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Only non-secret presentation assets and endpoint metadata may be copied into
# the desktop bundle. Python packages are collected by Analysis/hiddenimports;
# copying their source trees as data would bypass the trust boundary below.
a = Analysis(
    ['clients/desktop/main.py'],
    pathex=['.', 'clients/desktop', 'api_clients', 'ui', 'utils'],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('locales', 'locales'),
        ('clients/desktop/theme_manager.py', '.'),
        ('bagongpilipinas.png', '.'),
        ('office_logo.png', '.'),
        ('server_config.json', '.'),
    ],
    hiddenimports=[
        'requests',
        'urllib3',
        'websocket',
        'websocket._abnf',
        'websocket._app',
        'websocket._core',
        'websocket._exceptions',
        'websocket._handshake',
        'websocket._http',
        'websocket._logging',
        'websocket._socket',
        'websocket._ssl_compat',
        'websocket._url',
        'websocket._utils',
        'certifi',
        'charset_normalizer',
        'idna',
        'customtkinter',
        'tkinter',
        'tkinter.ttk',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.figure',
        'matplotlib.ticker',
        'pandas',
        'openpyxl',
        'utils',
        'utils.metrics',
        'api_clients.api_helper',
        'api_clients.auth_service',
        'api_clients.billing_service',
        'api_clients.client_config',
        'api_clients.client_logger',
        'api_clients.import_service',
        'api_clients.offline_manager',
        'api_clients.payment_service',
        'api_clients.portfolio_service',
        'api_clients.property_service',
        'api_clients.readiness_service',
        'api_clients.reports_service',
        'api_clients.search_service',
        'api_clients.sync_monitor',
        'api_clients.system_service',
        'ui.analytics_dashboard',
        'ui.animation_helper',
        'ui.assessment_roll',
        'ui.assessments',
        'ui.audit_trail',
        'ui.batch_delete_payments',
        'ui.command_palette',
        'ui.compliant_dashboard',
        'ui.conflict_resolver',
        'ui.dashboard_home',
        'ui.delinquency_dashboard',
        'ui.dossier',
        'ui.help_page',
        'ui.import_wizard',
        'ui.ledger',
        'ui.logs',
        'ui.navigation',
        'ui.notifications',
        'ui.portfolio',
        'ui.property',
        'ui.rate_limiting',
        'ui.recycle',
        'ui.reports',
        'ui.status_bar',
        'ui.system_admin',
        'ui.system_health',
        'ui.users',
        'ui.watchdog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'alembic',
        'backend',
        'boto3',
        'botocore',
        'database_hardening_tool',
        'dotenv',
        'migration_manager',
        'pymysql',
        'pytest',
        'scripts.recover_mariadb_root',
        'scripts.rotate_server_credentials',
        'sqlalchemy',
        'utils.config',
        'utils.db_compat',
        'utils.logger',
        'utils.secrets_manager',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Treasury',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/official/app_icon.ico',
)
